export const FAVORITES_KEY = 'favorites';
export const THEME_KEY = 'theme';
export const SERVER_URL = 'http://localhost:3000';

export const CITIES: { [key: string]: string } = {
  almaty: 'Алматы',
  astana: 'Астана',
  shymkent: 'Шымкент',
  aktobe: 'Актобе',
  atyrau: 'Атырау',
  karaganda: 'Караганда',
  kostanay: 'Костанай',
  kyzylorda: 'Кызылорда',
  pavlodar: 'Павлодар',
  petropavl: 'Петропавл',
  oral: 'Орал',
  oskemen: 'Өскемен',
  taraz: 'Тараз',
  turkistan: 'Түркістан',
  semey: 'Семей',
  ekibastuz: 'Экибастуз',
  temirtau: 'Темиртау',
  rudny: 'Рудный',
  balqash: 'Балқаш',
  zhanaozen: 'Жаңаөзен',
  zharkent: 'Жаркент',
  kokshetau: 'Көкшетау',
  taldykorgan: 'Талдықорған',
  stepnogorsk: 'Степногорск',
  sariagash: 'Сарыағаш',
  zhezkazgan: 'Жезқазған',
  aksu: 'Ақсу',
  shchuchinsk: 'Щучинск',
  lisakovsk: 'Лисаковск',
  kentau: 'Кентау',
  saran: 'Сарань',
  akkol: 'Ақкөл',
  zaysan: 'Зайсан',
  makinsk: 'Макинск',
  ayagoz: 'Аягөз',
  shemonaikha: 'Шемонаиха',
  zhetysay: 'Жетісай',
  turkestan: 'Түркістан',
};
